-- streets.lua
-- Returns a table of LA-inspired street names for roleplay.

local streets = {
    -- Main / boulevards
    "Alta Vista Blvd",
    "Imperial Highway",
    "Pico Vista Blvd",
    "Westmont Avenue",
    "Beverly Crest Drive",
    "Arroyo Grande Blvd",
    "Magnolia Avenue",
    "Eastland Blvd",
    "Sunset Parkway",
    "Vinewood Boulevard",
    "Hearthside Boulevard",
    "Ridgecrest Drive",
    "Montclair Avenue",
    "Crown Heights Blvd",
    "Capitol Way",
    "Redondo Parkway",

    -- Neighborhood / residential
    "Echo Glen Drive",
    "Cypress View Street",
    "La Palma Court",
    "Vinehill Avenue",
    "Palisade Terrace",
    "Sepulva Avenue",
    "Mariposa Lane",
    "La Mesa Drive",
    "Pershing Place",
    "Glenwood Row",
    "Orchid Lane",
    "Sagebrush Way",
    "Huntington Hollow",
    "Maplecrest Drive",
    "Ivywood Court",
    "Brentwood Lane",
    "Sunnyside Crescent",
    "Willowbend Terrace",
    "Cedar Bluff Road",

    -- Industrial / downtown
    "Alameda Row",
    "Union Freight Street",
    "Harbor View Blvd",
    "Warehouse Lane",
    "Terminal Avenue",
    "Grand Union Drive",
    "Skidmore Street",
    "Dockside Passage",
    "Foundry Road",
    "Railspur Avenue",

    -- Coastal / beach
    "Pacific Crest Drive",
    "Marina Vista Blvd",
    "Seabreeze Avenue",
    "Pierpoint Street",
    "Paloma Beach Drive",
    "Oceanfront Parkway",
    "Bay Harbor Road",
    "Coral Way",
    "Tideview Promenade",
    "Sandbar Lane",

    -- Mountain / hillside
    "Griffin Ridge Road",
    "Crestline Terrace",
    "Windward Pass",
    "Eaglecrest Drive",
    "Hillside Vista",

    -- Short streets / alleys / courts
    "Juniper Court",
    "Olive Way",
    "Fletcher Alley",
    "Roxbury Court",
    "Beacon Alley",
    "Pine Hollow Lane",

    -- Scenic / park-adjacent
    "Riverside Walk",
    "Parkview Avenue",
    "Sycamore Walk",
    "Garden Court",
    "Heritage Lane",

    -- Mixed-use / trendy
    "Mercer Row",
    "Haven Street",
    "Founders Walk",
    "Depot Row",
    "Broadstone Avenue",

    -- Other LA-flavored but mostly fictional names
    "Laurel Heights Drive",
    "Canyon View Blvd",
    "Northbridge Avenue",
    "Westgate Avenue",
    "Southport Road",
    "El Dorado Way",
    "Monarch Boulevard",
    "Hillcrest Avenue",
    "Vermillion Drive",
    "Sable Street",
    "Goldenleaf Drive",
    "Rosada Lane",
    "Valencia Road",
    "Coronado Avenue",
    "Granite Way",
    "Marquette Drive",
    "Del Rey Boulevard",
    "Carmel Court",
    "Riviera Place",
    "Bluffside Road",

    -- More filler names to give a wide variety for mapping / addresses
    "Hillsborough Drive",
    "Cedarcrest Avenue",
    "Cascade Lane",
    "Brigantine Way",
    "Oceanview Terrace",
    "Sandstone Ave",
    "Ridgepoint Drive",
    "Lakeside Boulevard",
    "Fairmont Street",
    "Sequoia Drive",
    "Meridian Avenue",
    "Sunrise Lane",
    "Moonlight Drive",
    "Harborcrest Road",
    "Eastwood Avenue",
    "Westlake Road",
    "Northshore Drive",
    "Southwell Street",
    "Beacon Hill Road",
    "Crosswind Boulevard",
    "Palisades Lane",
    "Vista del Mar",
    "Cobalt Avenue",
    "Alvarado Street",
    "Carmine Way",
    "Briarcliff Road",
    "Highland Grove",
    "Old Mill Lane",
    "Prospect Terrace",
    "Torrance Way",
    "Midtown Place",
    "Harwood Avenue",
    "Grove Park Lane",
    "Laurel Creek Road",
    "Ridgeview Boulevard",
    "Elm Creek Drive",
    "Crown Ridge Lane",
    "Sunnybrook Ave",
    "Eastgate Passage",
    "Marigold Way",
    "Cove Point Street",
    "Silverbell Road",
    "Copperfield Lane",
    "Belmont Row",
    "Fairview Court",
    "Horizon Avenue",
    "Bayside Drive",
    "Linden Boulevard",
    "Crescent Point",
    "Orchard Bend",
    "Garnet Street",
    "Horizon Crest",
    "Maple Grove Road",
    "Northfield Drive",
    "Westberry Lane",
    "Seafarer Road",
    "Corwin Street",
    "Victorian Way",
    "Evergreen Terrace",
    "Beacon Harbor",
    "Ridgewalk Lane",
    "Quarry Road",
    "Sierra View Drive",
    "Mesa Verde Lane",
}

return streets